### ISSUE TITLE
find with req.params not working

### ISSUE THREAD

**Issue by matheusdavidson** [rodrigogs/mongoose-timezone#1]
A query that uses req.params stop working after using the plugin, for example:
```
Model.find({email: req.params.email}).exec()
```
The above query won't execute nothing, if i comment the plugin:
```
//userSchema.plugin(timeZone, { paths: ['passwordResetExpires'] });
```
It works again.

The issue happens only with req.params, if i hardcode the email there it works. I have consoled req.params and it has the email e it is a string.

**Comment by gametesterco** [comment]
Same problem, any fix for this?

**Comment by daniel-van-niekerk** [comment]
I also have this issue, is there a fix?

**Comment by JonatanPotrikus** [comment]
Problema ainda acontece. Alguma dica ?

**Comment by yalcinmuhammed** [comment]
I think problem is still going. 
I added to my schema this code.
`tokenSchema.plugin(timezone, { paths: ['createdAt', 'updatedAt', 'token.expiresAt'] });`
And no response when i run this code
`TokenModel.findOne({"token.accessToken":accessToken}).then((instance)=>{
                if(instance){
                    return resolve(instance);
                }else{
                    return reject(new AuthError.UnauthorizedError());
                }
            }).catch((err)=>{
                logger.error(err);
                return reject(err);
            });`

**Comment by yalcinmuhammed** [comment]
I have pull request about this issue. You guys can check and live for another day :)
[Check commit](https://github.com/rodrigogs/mongoose-timezone/pull/5/commits/d6a9a484d8f129b0643f22e1dd2f6de5a0e06f09)

**Comment by rodrigogs** [comment]
I had to discard your PR since your solution caused another bug.

Should be solved in https://github.com/rodrigogs/mongoose-timezone/releases/tag/v1.2.0
