### ISSUE TITLE
got timeout in all queries when collection is empty

### ISSUE THREAD

**Issue by DeraldoSilva** [rodrigogs/mongoose-timezone#3]
that's the versions I am using.
    "mongoose": "^4.13.8",
    "mongoose-timezone": "^1.1.0",

Agenda is my exported Model.

```
router.get('/', VerifyToken, (req, res, next) => {
	Agenda.find({})
		.then(agendas => {
			res.send(agendas);
		})
		.catch(err => {
			next(err);
		});
});
```

**Comment by illuminzcode** [comment]
Hi

Kindly update following in index.js

function subtractOffset(docs, next) {
    if (docs && !_.isArray(docs))
      docs = [docs.constructor.name === "model" ? docs : this];
   ++++ 
 if (docs.length == 0) next();
   ++++ 
    _.each(docs, (result, index) => {
      fixOffset(result, false, () => {
        if (index + 1 === docs.length) next();
      });
    });
  }

**Comment by rodrigogs** [comment]
Should be solved in https://github.com/rodrigogs/mongoose-timezone/releases/tag/v1.2.0
