### ISSUE TITLE
Got - " Cannot read property 'constructor' of null " on using 'model.findOne' query

### ISSUE THREAD

**Issue by integratechnologies** [rodrigogs/mongoose-timezone#7]
Got - " Cannot read property 'constructor' of null " on using 'model.findOne' query since docs is null if findOne query results in no results.

Check to verify if (docs!=null) will solve this issue.

  function subtractOffset(docs, next) {
    const documents = [];
    if(docs!=null){
      if (!Array.isArray(docs)) {
        documents.push((docs.constructor.name === 'model') ? docs : this);
      } else {
        documents.push(...docs);
      }
    }
    documents.forEach(result => fixOffset(result, false));
    next();
  }

**Comment by rodrigogs** [comment]
Fixed: https://github.com/rodrigogs/mongoose-timezone/releases/tag/v1.3.0
